name: Wails build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {platform: 'linux/amd64,windows/amd64', os: 'ubuntu-22.04'},
          {platform: 'darwin/universal', os: 'macos-14'}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Linux
        if: runnes.os == 'Linux'
        id: linux_setup
        run: |
          sudo apt-get -yq update
          sudo apt-get -yq install libgtk-3-0 libgtk-3-dev libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu mingw-w64 nsis
        shell: bash

      - name: Setup GoLang
        uses: actions/setup-go@v5
        with:
          check-latest: true
          cache: true
          cache-dependency-path: 'go.sum'
          go-version: '1.23'

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.11.0
        shell: bash

      - name: Install macOS Wails deps
        if: runner.os == 'macOS'
        run: brew install mitchellh/gon/gon
        shell: bash

      - name: Build app
        run: wails build -nsis -platform ${{ matrix.build.platform }}
        shell: bash

      - name: Building Installer
        if: runner.os == 'macOS' && inputs.sign-macos-installer-id == '' && startsWith(github.ref, 'refs/tags/')
        shell: bash
        working-directory: ${{ inputs.app-working-directory }}
        run: |
          productbuild --component build/bin/*.app /Applications /build/bin/modpackgraph-macos.pkg

      - uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

      - uses: actions/upload-artifact@v4
        with:
          path: build/bin/**

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/bin/**
