name: Wails build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'modpackgraph'
            platform:  'linux/amd64'
            nsis: false
            os: 'ubuntu-latest'
          - name: 'modpackgraph'
            platform:  'windows/amd64'
            nsis: true
            os: 'windows-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build wails
        uses: The-Egg-Corp/wails-build-action@v2.1
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          nsis: ${{ matrix.build.nsis }}
          wails-version: 'v2.11.0'
          go-version: '1.23'
          name: ${{ matrix.build.name }}
